spring:
  kafka:
    consumer:
      enable-auto-commit: true
      auto-commit-interval: 1000
      max-poll-records: 15
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: closememo-query

---

spring:
  config:
    activate:
      on-profile: local

  kafka:
    bootstrap-servers: 127.0.0.1:9092

---

spring:
  config:
    activate:
      on-profile: dev

  kafka:
    bootstrap-servers: dev.kafka1.closememo.com:19092

---

spring:
  config:
    activate:
      on-profile: real

  kafka:
    bootstrap-servers: kafka1.closememo.com:19092
