
spring:
  config:
    activate:
      on-profile: "!real"

elasticsearch:
  configs:
    default:
      host-name: dev.es.closememo.com
      port: 9200
      connection-timeout: 5000
      socket-timeout: 60000

management:
  health:
    elasticsearch:
      enabled: false

---

spring:
  config:
    activate:
      on-profile: real

elasticsearch:
  configs:
    default:
      host-name: es.closememo.com
      port: 9200
      connection-timeout: 5000
      socket-timeout: 60000
