
spring:
  application:
    name: query
  profiles:
    active: local
    include: actuator, datasource, elasticsearch, kafka, logging, openapi, secret
  cache:
    type: redis

server:
  port: 10082
  shutdown: graceful
