
spring:
  config:
    activate:
      on-profile: "!real"

elasticsearch:
  configs:
    default:
      host-name: dev.es.bitgadak.com
      port: 9200
      connection-timeout: 5000
      socket-timeout: 60000

---

spring:
  config:
    activate:
      on-profile: real

elasticsearch:
  configs:
    default:
      host-name: es.bitgadak.com
      port: 9200
      connection-timeout: 5000
      socket-timeout: 60000
