
---

spring:
  config:
    activate:
      on-profile: "!real"

secret:
  system-key: ${DEV_SYSTEM_KEY}

---

spring:
  config:
    activate:
      on-profile: real

secret:
  system-key: ${SYSTEM_KEY}
